config/routes.rb
Wpg::Application.routes.draw do

  get "about" => "static_pages#about", :as => "about"
  get "get_started" => "static_pages#get_started", :as => "get_started"
  get "home" => "home#home", :as => "home"
  get "landing" => "static_pages#landing", :as => "landing"
  
  resources :sessions, only: [:new, :create, :destroy]

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"

  
  resources :games
  resources :users

  get "weeks/one"
  get "weeks/two"
  get "weeks/three"
  get "weeks/four"
  get "weeks/five"
  get "weeks/six"
  get "weeks/seven"
  get "weeks/eight"
  get "weeks/nine"
  get "weeks/ten"
  get "weeks/eleven"
  get "weeks/twelve"

  get "overview" => "static_pages#overview", :as => "overview"
  get "crisis" => "static_pages#crisis", :as => "crisis"
  get "setup" => "static_pages#setup", :as => "setup"
  get "materials" => "static_pages#materials", :as => "materials"
  get "learn" => "static_pages#learn", :as => "learn"
  get "procedures" => "static_pages#procedures", :as => "procedures"

  root 'static_pages#landing'

  

end

app/models/country.rb
class Country < ActiveRecord::Base
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :user
  has_many :countries

  accepts_nested_attributes_for :countries
end

app/models/student.rb
class Student < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_one :game
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def new
    @game = Game.new
    @game.countries.build
  end

  def create
    game = Game.new(game_params)
    current_user.game = game
    if game.save
      redirect_to home_url
    else
      render action: 'new'
    end
  end

  def show
    @game = Game.find(params[:id])
  end

  private
    def game_params
      params.require(:game).permit(:name, :saboteur, :weather_god, countries_attributes: [:id, :secretary_of_state, :name, :defense_minister, :comptroller, :secretary_of_trade, :prime_minister])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
    if not current_user
      redirect_to landing_url
      return
    end
    if current_user.game
      redirect_to weeks_one_url
    end
  end

  def test
    # render layout: false
    render layout: false, :file => 'public/land.html' and return
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to home_url
    else
      flash.now[:error] = "Invalid login credentials."
      render action: 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def landing
    render layout: false
  end

  def get_started
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to home_url
    else
      render action: 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/weeks_controller.rb
class WeeksController < ApplicationController
  def one
    @game = current_user.create_game
  end

  def two
  end

  def three
  end

  def four
  end

  def five
  end

  def six
  end

  def seven
  end

  def eight
  end

  def nine
  end

  def ten
  end

  def eleven
  end

  def twelve
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/weeks_helper.rb
module WeeksHelper
end

app/views/games/create.html.haml
%h1 Games#create
%p Find me in app/views/games/create.html.haml

app/views/games/new.html.haml
- provide(:title, "New Game")
.row
  .col-md-8.col-md-offset-2
    .box
      = render 'form'

app/views/home/home.html.haml
- provide(:title, "Home")
.row
  .col-md-10.col-md-offset-1
    .box
      %h3 Welcome!
      %p Welcome to the world peace game.  For more information please check out the following resources:
      %ul
        %li
          = link_to "Getting Started", get_started_path
        %li
          = link_to "Game rules", "#"
        %li
          = link_to "Resources", "#"
      .start-game
        = link_to "Start new game", weeks_one_path, :class => "btn btn-lg btn-custom"

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default.navbar-static-top{role: "navigation"}
  .container
    .navbar-header
      = link_to (image_tag 'logo.png', :class => 'nav-logo') + "World Peace Game", home_path, class: "nav-text"
    #collapse_links.collapse.navbar-collapse.right-links
      %ul.nav.nav-pills.navbar-right
        - if current_user
          %li
            = link_to 'Logout', logout_path
        - else
          %li
            = link_to 'Login', login_path
        %li
          = link_to 'About', overview_path

app/views/layouts/_shim.html.haml
/[if lt IE 9]
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>

app/views/static_pages/landing.html.haml
!!!
%html
  %head
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "WPG - Teacher"
    %meta{content: content_for?(:description) ? yield(:description) : "WPG", name: "description"}
    = favicon_link_tag
    = stylesheet_link_tag "application", :media => "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => false

    = stylesheet_link_tag "//netdna.bootstrapcdn.com/bootstrap/3.0.1/css/bootstrap.min.css"
    = stylesheet_link_tag "//netdna.bootstrapcdn.com/bootstrap/3.0.1/css/bootstrap-theme.min.css"
    = javascript_include_tag "//netdna.bootstrapcdn.com/bootstrap/3.0.1/js/bootstrap.min.js"  

    = csrf_meta_tags
    = render 'layouts/shim'
  %body
    #header
      = render 'layouts/header' unless @disable_nav
    #body
      .landing-first
        #vid.container_16
          .grid_12.push_2
            %iframe{allowfullscreen: "", frameborder: "0", height: "360", src: "//www.youtube.com/embed/lCq8V2EhYs0?rel=0", width: "640"}
      .landing-second
        .hotfix
          / quote and why world peace game
          #block1.container_16
            .grid_6.alpha.push_1
              %img{src: "land/quote.png"}/
            .grid_8.push_2
              %h1.landing Why The World Peace Game?
              #why.grid_7.alpha
                %img{src: "land/why.png"}/
                %p
                  Students will also learn to:
                %ul
                  %li Negotiate and compromise
                  %li Make decisions under pressure
                  %li Balance multiple conflicts and motivations
                  %li Break down large problems into solvable units
      .landing-third
        / about the world peace game
        .container_16
          %h1.landing#about.push_4 About The World Peace Game
          .grid_16.alpha.omega
            #boutText.grid_6
              The World Peace Game is a hands-on political simulation that gives players the opportunity to explore the connectedness of the global community through the lens of the economic, social, and environmental crises and the imminent threat of war. The goal of the game is to extricate each country from dangerous circumstances and achieve global prosperity with the least amount of military intervention. As “nation teams,” students will gain greater understanding of the critical impact of information and how it is used.
            %img{src: "land/pic1.png"}/
          #bout2.grid_16
            .grid_6.alpha
              %img{src: "land/pic2.png"}/
            #boutText.grid_10.alpha.omega
              As their teams venture further into this interactive social setting laced with highly charged philosophical issues, the skills needed to identify ambiguity and bias in the information they receive will be enhanced and more specifically they will rapidly perceive that reactive behavior not only provokes antagonism, it can leave them alone and isolated in the face of powerful enemies. Beliefs and values will evolve or completely unravel as they begin to experience the positive impact and windows of opportunity that emerge through effective collaboration and refined communication.
              In essence, as meaning is constructed out of chaos and new creative solutions are proposed, World Peace Game players will learn to live and work comfortably at the frontiers of the unknown.
      .landing-fourth
        / john hunter's ted talk
        .container_16
          %h2.landing John Hunter's TED Talk
          .bottomText
            Listen to John Hunter, the founder of The World Peace Game,
            = succeed "talk" do
              %br/
          #TED{align: "center"}
            %iframe{allowfullscreen: "", frameborder: "0", height: "360", src: "//www.youtube.com/embed/0_UTgoPUTLQ?rel=0", width: "640"}
          #bottom.bottomText
            Want more information about The World Peace Game? Visit
            %a{href: "https://www.worldpeacegame.org/"} www.worldpeacegame.org

    #footer.container
      = render 'layouts/footer' unless @disable_footer
















/ .row
/   .col-md-12
/     .box
/       .row
/         .col-md-7
/           %iframe{allowfullscreen: "", frameborder: "0", height: "315", src: "//www.youtube.com/embed/lCq8V2EhYs0", width: "560"}
/         .col-md-5
/           %h1 World Peace Game
/           .landing-action
/             = image_tag 'logo.png'
/             = link_to "Login", login_path, :class => "btn btn-lg btn-custom"
/             = link_to "Register", signup_path, :class => "btn btn-lg btn-custom"
/       .row.top-buffer
/         .col-md-7
/           %h2 Why the World Peace Game
/           %p In the words of John Hunter, the World Peace Game (WPG) is a teaching tool: 
/           %p "It is not an entertainment or a diversion for idle minds, because its main purpose is really as a teaching vehicle: helping kids to develop conceptual plans, design and implement them, push innovative and creative thinking, help them to formulate ideas and be able to express them concisely and persuasively, to be able to ‘deal‘ with adults on equal footing in conversation and to the extent possible conceptually and philosophically, to foster regular reflective practice, and of course, to foster compassion."
/         .col-md-5
/           = image_tag "landing-1.jpg", class: "landing-image"
/       .row.top-buffer
/         .col-md-6
/           = image_tag "landing-2.jpg", class: "landing-image"
/         .col-md-6
/           %p Your students will already be using the game to learn the larger concepts that John just pointed out. The WPG is truly incredible, however, because the game also gives you freedom to integrate core curriculum requirements. Think of the game as scaffolding for the teaching objectives that you have. Through play students achieve these objectives in a measurable way. 
/           %p Students learn to
/           %ul
/             %li Communicate, negotiate, and compromise
/             %li Make decisions under pressure
/             %li Set, enforce, and comply with standards of online behavior
/             %li Balance multiple conflicts and motivations
/             %li Chunk a larger problem into manageable pieces
/       .row.top-buffer
/         .col-md-5
/           %h2 Overview
/           %p Students take on roles as leaders in countries of various wealth, members of the World Bank, Arms Dealers, and various other positions. Each game day, countries take turns making declarations, followed by a period for negotiation after each declaration. The World Peace Game is played by constant discussion and negotiation. The game is won when the countries have worked to solve a list of crisis and every country has a net gain.
/         .col-md-7
/           .video.pull-right
/             %iframe{allowfullscreen: "", frameborder: "0", height: "315", src: "//www.youtube.com/embed/0_UTgoPUTLQ?rel=0", width: "560"}

app/views/users/_form.html.haml
= form_for @user do |f|
  .form-group
    = f.text_field :email, class: "form-control", placeholder: "Email"
  .form-group
    = f.password_field :password, class: "form-control", placeholder: "Password"
  .form-group
    = f.password_field :password_confirmation, class: "form-control", placeholder: "Password confirmation"
  = f.submit "Create", class: "btn btn-custom"

app/views/users/create.html.haml
%h1 Users#create
%p Find me in app/views/users/create.html.haml

app/views/weeks/eight.html.haml
- provide(:title, "Week 8")
.row
  .col-md-10.col-md-offset-1
    .box
      %h1 Week 8
      %h3 Prepare before class
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

      %h3 In class activities
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

      %h3 Prepare for next class
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

      .bottom-links
        .previous-week.pull-left
          = link_to "Last week", weeks_seven_path
        .next-week.pull-right
          = link_to "Next week", weeks_nine_path

app/views/weeks/eleven.html.haml
- provide(:title, "Week 11")
.row
  .col-md-10.col-md-offset-1
    .box
      %h1 Week 11
      %h3 Prepare before class
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

      %h3 In class activities
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

      %h3 Prepare for next class
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

      .bottom-links
        .previous-week.pull-left
          = link_to "Last week", weeks_ten_path
        .next-week.pull-right
          = link_to "Next week", weeks_twelve_path

app/views/weeks/five.html.haml
- provide(:title, "Week 5")
.row
  .col-md-10.col-md-offset-1
    .box
      %h1 Week 5
      %h3 Prepare before class
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

      %h3 In class activities
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

      %h3 Prepare for next class
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

      .bottom-links
        .previous-week.pull-left
          = link_to "Last week", weeks_four_path
        .next-week.pull-right
          = link_to "Next week", weeks_six_path

app/views/weeks/four.html.haml
- provide(:title, "Week 4")
.row
  .col-md-10.col-md-offset-1
    .box
      %h1 Week 4
      %h3 Prepare before class
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

      %h3 In class activities
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

      %h3 Prepare for next class
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

      .bottom-links
        .previous-week.pull-left
          = link_to "Last week", weeks_three_path
        .next-week.pull-right
          = link_to "Next week", weeks_five_path

app/views/weeks/nine.html.haml
- provide(:title, "Week 9")
.row
  .col-md-10.col-md-offset-1
    .box
      %h1 Week 9
      %h3 Prepare before class
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

      %h3 In class activities
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

      %h3 Prepare for next class
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

      .bottom-links
        .previous-week.pull-left
          = link_to "Last week", weeks_eight_path
        .next-week.pull-right
          = link_to "Next week", weeks_ten_path

app/views/weeks/one.html.haml
- provide(:title, "Week 1")
.row
  .col-md-3
    .box.side-nav
      %ul.nav.nav-pills.nav-stacked
        %li
          %a{href: weeks_one_path} Today (Week 1)
        %li
          %a{href: game_path(current_user.game)} Game status
        %li
          %a{href: procedures_path} Procedures and resources
  .col-md-9
    .box
      %h1 Week 1
      .week-video
        %iframe{allowfullscreen: "", frameborder: "0", height: "315", src: "//www.youtube.com/embed/iOC0mrmIjHo?rel=0", width: "560"}
      .blockquote.week-quote
        "There is no instance of a country having benefited from prolonged warfare." ― Sun Tzu, The Art of War

      %h3 Prepare before class
      %ul
        %li Decide on roles for kids. As the facilitator your most important duty is picking the team leaders, saboteur, and weather god[ess]. Remember the students get to pick their cabinet. When creating a game under the _____ tab, you will be able to see all of the roles that must be assigned. Here are some helpful suggestions from John on picking your leaders for the different roles:
        %ul
          %li Pick students based on the idea that the particular role will be beneficial for that individual’s growth.
          %li If your intuition indicates that the student is a budding leader, you can encourage this by giving them an important leadership position. The game can help solidify leadership skills. 
          %li If the age of your students varies greatly, sometimes, pick younger kids as leaders so the older kids do not overshadow them. 
          %li Print out Dossiers to be given out in class.


      %h3 In class activities
      %ul
        %li Show Game Intro (Video?): Showing how the game is played can get them excited.
        %li Show students the game board with the 5 different countries. Explain the setup of the board and the meaning of all of the game pieces. 
        %li Assign Roles #{link_to 'here', new_game_path(current_user.game)}
        %ul
          %li Ask students chosen for the roles of prime minister and weather god[ess]. Remember the students can accept or reject your offer. 
          %li Declare the final roles to the class.
          %li The prime ministers will then draft their cabinets.
          %li Tell kids about the roll of the saboteur. Secretively, ask a student to be the saboteur before the next game day.
        %li Hand out dossiers based on rolls.
        %li Students should design flags and designate name of their countries.


      %h3 Prepare for next class
      %ul
        %li To go through the dossier and online video (we make these?) to understand their role in the game

      .bottom-links
        .next-week.pull-right
          = link_to "Next week", weeks_two_path

app/views/weeks/seven.html.haml
- provide(:title, "Week 7")
.row
  .col-md-10.col-md-offset-1
    .box
      %h1 Week 7
      %h3 Prepare before class
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

      %h3 In class activities
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

      %h3 Prepare for next class
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

      .bottom-links
        .previous-week.pull-left
          = link_to "Last week", weeks_six_path
        .next-week.pull-right
          = link_to "Next week", weeks_eight_path

app/views/weeks/six.html.haml
- provide(:title, "Week 6")
.row
  .col-md-10.col-md-offset-1
    .box
      %h1 Week 6
      %h3 Prepare before class
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

      %h3 In class activities
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

      %h3 Prepare for next class
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

      .bottom-links
        .previous-week.pull-left
          = link_to "Last week", weeks_five_path
        .next-week.pull-right
          = link_to "Next week", weeks_seven_path